=== api-evangelist/amazon-cloudsearch/json-schema/cloudsearch-domain-status-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-cloudsearch/refs/heads/main/json-schema/cloudsearch-domain-status-schema.json",
  "title": "DomainStatus",
  "description": "DomainStatus schema",
  "type": "object",
  "properties": {
    "DomainId": {
      "type": "string"
    },
    "DomainName": {
      "type": "string"
    },
    "ARN": {
      "type": "string"
    },
    "Created": {
      "type": "boolean"
    },
    "Deleted": {
      "type": "boolean"
    },
    "Processing": {
      "type": "boolean"
    },
    "RequiresIndexDocuments": {
      "type": "boolean"
    },
    "SearchInstanceCount": {
      "type": "integer"
    },
    "SearchInstanceType": {
      "type": "string"
    },
    "DocService": {
      "type": "object",
      "properties": {
        "Endpoint": {
          "type": "string"
        }
      }
    },
    "SearchService": {
      "type": "object",
      "properties": {
        "Endpoint": {
          "type": "string"
        }
      }
    }
  }
}

=== api-evangelist/amazon-cloudsearch/examples/cloudsearch-domain-status-example.json
{
  "DomainId": "abc12345",
  "DomainName": "example-resource",
  "ARN": "arn:aws:::example/abc12345",
  "Created": true,
  "Deleted": true,
  "Processing": true,
  "RequiresIndexDocuments": true,
  "SearchInstanceCount": 100,
  "SearchInstanceType": "example-value",
  "DocService": {
    "Endpoint": "example-value"
  },
  "SearchService": {
    "Endpoint": "example-value"
  }
}
